# Generated by Django 5.2.9 on 2026-01-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_add_file_hash_and_size'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='resumedocument',
            new_name='resumes_res_uploade_437460_idx',
            old_name='resumes_res_uploade_idx',
        ),
        migrations.AddField(
            model_name='parserun',
            name='requirements',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
