# Generated by Django 5.2.9 on 2026-01-26 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_rename_resumes_res_uploade_idx_resumes_res_uploade_437460_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParseRunStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=20, null=True)),
                ('new_status', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='parserun',
            name='progress_stage',
            field=models.CharField(choices=[('queued', 'Queued'), ('extracting_pii', 'Extracting PII'), ('calling_llm', 'Calling LLM'), ('validating', 'Validating'), ('classifying', 'Classifying'), ('summarizing', 'Summarizing'), ('persisting', 'Persisting'), ('complete', 'Complete')], default='queued', max_length=20),
        ),
        migrations.AddField(
            model_name='parserun',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parserun',
            name='task_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parserun',
            name='task_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parserun',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='resumedocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='parserun',
            index=models.Index(fields=['status'], name='resumes_par_status_6f9adc_idx'),
        ),
        migrations.AddIndex(
            model_name='parserun',
            index=models.Index(fields=['created_at'], name='resumes_par_created_1005c0_idx'),
        ),
        migrations.AddIndex(
            model_name='parserun',
            index=models.Index(fields=['resume_document', 'status'], name='resumes_par_resume__6da603_idx'),
        ),
        migrations.AddIndex(
            model_name='parserun',
            index=models.Index(fields=['resume_document', '-created_at'], name='resumes_par_resume__75c8fc_idx'),
        ),
        migrations.AddIndex(
            model_name='resumedocument',
            index=models.Index(fields=['created_at'], name='resumes_res_created_02f7a8_idx'),
        ),
        migrations.AddIndex(
            model_name='resumedocument',
            index=models.Index(fields=['uploaded_by', '-created_at'], name='resumes_res_uploade_dd2a18_idx'),
        ),
        migrations.AddField(
            model_name='parserunstatuslog',
            name='parse_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='resumes.parserun'),
        ),
        migrations.AddIndex(
            model_name='parserunstatuslog',
            index=models.Index(fields=['parse_run', '-changed_at'], name='resumes_par_parse_r_f1f353_idx'),
        ),
    ]
