# Generated by Django 5.2.9 on 2026-02-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_parserunstatuslog_parserun_progress_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parserun',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='queued', max_length=20),
        ),
    ]
