# Generated by Django 5.2.9 on 2026-01-26 19:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
        ('resumes', '0004_parserunstatuslog_parserun_progress_stage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateEditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('changes', models.JSONField()),
                ('before_snapshot', models.JSONField(blank=True, null=True)),
                ('after_snapshot', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['created_at'], name='candidates__created_a71da5_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['primary_role'], name='candidates__primary_a88b0b_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['overall_confidence'], name='candidates__overall_735a9a_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['seniority'], name='candidates__seniori_d40b53_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['resume_document', '-created_at'], name='candidates__resume__1c08dd_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['parse_run', '-created_at'], name='candidates__parse_r_3a1805_idx'),
        ),
        migrations.AddIndex(
            model_name='educationentry',
            index=models.Index(fields=['institution'], name='candidates__institu_8bd0f0_idx'),
        ),
        migrations.AddIndex(
            model_name='educationentry',
            index=models.Index(fields=['degree'], name='candidates__degree_a52d20_idx'),
        ),
        migrations.AddIndex(
            model_name='experienceentry',
            index=models.Index(fields=['company'], name='candidates__company_c6fa87_idx'),
        ),
        migrations.AddIndex(
            model_name='experienceentry',
            index=models.Index(fields=['title'], name='candidates__title_1a299f_idx'),
        ),
        migrations.AddIndex(
            model_name='experienceentry',
            index=models.Index(fields=['is_current'], name='candidates__is_curr_b4828b_idx'),
        ),
        migrations.AddIndex(
            model_name='experienceentry',
            index=models.Index(fields=['candidate', 'is_current', '-start_date'], name='candidates__candida_3d6a40_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['name'], name='candidates__name_0acdbd_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['candidate', 'name'], name='candidates__candida_b9c584_idx'),
        ),
        migrations.AddField(
            model_name='candidateeditlog',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_logs', to='candidates.candidate'),
        ),
        migrations.AddField(
            model_name='candidateeditlog',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_edits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='candidateeditlog',
            index=models.Index(fields=['-edited_at'], name='candidates__edited__5258b9_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateeditlog',
            index=models.Index(fields=['candidate', '-edited_at'], name='candidates__candida_e465e9_idx'),
        ),
    ]
